/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import { be_ } from '@ctx-core/object'
import type { auth0_Ctx } from './auth0_Ctx'
import type { AUTH0_CLIENT_ID$_T } from './AUTH0_CLIENT_ID$_b'
import { AUTH0_CLIENT_ID$_b } from './AUTH0_CLIENT_ID$_b'
import type { AUTH0_DOMAIN$_T } from './AUTH0_DOMAIN$_b'
import { AUTH0_DOMAIN$_b } from './AUTH0_DOMAIN$_b'
import type { AUTH0_URL$_T } from './AUTH0_URL$_b'
import { AUTH0_URL$_b } from './AUTH0_URL$_b'
import type { auth0_change_password_opened$_T } from './auth0_change_password_opened$_b'
import { auth0_change_password_opened$_b } from './auth0_change_password_opened$_b'
import type { auth0_closed$_T } from './auth0_closed$_b'
import { auth0_closed$_b } from './auth0_closed$_b'
import type { auth0_email$_T } from './auth0_email$_b'
import { auth0_email$_b } from './auth0_email$_b'
import type { auth0_forgot_password_check_email_opened$_T } from './auth0_forgot_password_check_email_opened$_b'
import { auth0_forgot_password_check_email_opened$_b } from './auth0_forgot_password_check_email_opened$_b'
import type { auth0_forgot_password_opened$_T } from './auth0_forgot_password_opened$_b'
import { auth0_forgot_password_opened$_b } from './auth0_forgot_password_opened$_b'
import type { auth0_login_opened$_T } from './auth0_login_opened$_b'
import { auth0_login_opened$_b } from './auth0_login_opened$_b'
import type { auth0_logout_msg$_T } from './auth0_logout_msg$_b'
import { auth0_logout_msg$_b } from './auth0_logout_msg$_b'
import type { auth0_opened$_T } from './auth0_opened$_b'
import { auth0_opened$_b } from './auth0_opened$_b'
import type { auth0_opened_class$_T } from './auth0_opened_class$_b'
import { auth0_opened_class$_b } from './auth0_opened_class$_b'
import type { auth0_signup_opened$_T } from './auth0_signup_opened$_b'
import { auth0_signup_opened$_b } from './auth0_signup_opened$_b'
import type { auth0_token$_T } from './auth0_token$_b'
import { auth0_token$_b } from './auth0_token$_b'
import type { auth0_token_error$_T } from './auth0_token_error$_b'
import { auth0_token_error$_b } from './auth0_token_error$_b'
import type { auth0_token_error_txt$_T } from './auth0_token_error_txt$_b'
import { auth0_token_error_txt$_b } from './auth0_token_error_txt$_b'
import type { auth0_token_json$_T } from './auth0_token_json$_b'
import { auth0_token_json$_b } from './auth0_token_json$_b'
import type { auth0_userinfo$_T } from './auth0_userinfo$_b'
import { auth0_userinfo$_b } from './auth0_userinfo$_b'
import type { auth0_userinfo_auth0_token$_T } from './auth0_userinfo_auth0_token$_b'
import { auth0_userinfo_auth0_token$_b } from './auth0_userinfo_auth0_token$_b'
import type { auth0_userinfo_ctx$_T } from './auth0_userinfo_ctx$_b'
import { auth0_userinfo_ctx$_b } from './auth0_userinfo_ctx$_b'
import type { clear_auth0_token_T } from './clear_auth0_token_b'
import { clear_auth0_token_b } from './clear_auth0_token_b'
import type { clear_auth0_token_error_T } from './clear_auth0_token_error_b'
import { clear_auth0_token_error_b } from './clear_auth0_token_error_b'
import type { close_auth0_T } from './close_auth0_b'
import { close_auth0_b } from './close_auth0_b'
import type { get_jwks_json_T } from './get_jwks_json_b'
import { get_jwks_json_b } from './get_jwks_json_b'
import type { in_auth0_token$_T } from './in_auth0_token$_b'
import { in_auth0_token$_b } from './in_auth0_token$_b'
import type { is_auth0_loggedin$_T } from './is_auth0_loggedin$_b'
import { is_auth0_loggedin$_b } from './is_auth0_loggedin$_b'
import type { is_auth0_loggedout$_T } from './is_auth0_loggedout$_b'
import { is_auth0_loggedout$_b } from './is_auth0_loggedout$_b'
import type { logout_auth0_token_T } from './logout_auth0_token_b'
import { logout_auth0_token_b } from './logout_auth0_token_b'
import type { logout_auth0_token_error_T } from './logout_auth0_token_error_b'
import { logout_auth0_token_error_b } from './logout_auth0_token_error_b'
import type { open_auth0_forgot_password_T } from './open_auth0_forgot_password_b'
import { open_auth0_forgot_password_b } from './open_auth0_forgot_password_b'
import type { open_auth0_forgot_password_check_email_T } from './open_auth0_forgot_password_check_email_b'
import { open_auth0_forgot_password_check_email_b } from './open_auth0_forgot_password_check_email_b'
import type { open_auth0_login_T } from './open_auth0_login_b'
import { open_auth0_login_b } from './open_auth0_login_b'
import type { open_auth0_signup_T } from './open_auth0_signup_b'
import { open_auth0_signup_b } from './open_auth0_signup_b'
import type { post_auth0_auth_change_password_T } from './post_auth0_auth_change_password_b'
import { post_auth0_auth_change_password_b } from './post_auth0_auth_change_password_b'
import type { post_auth0_dbconnections_change_password_T } from './post_auth0_dbconnections_change_password_b'
import { post_auth0_dbconnections_change_password_b } from './post_auth0_dbconnections_change_password_b'
import type { post_auth0_dbconnections_signup_T } from './post_auth0_dbconnections_signup_b'
import { post_auth0_dbconnections_signup_b } from './post_auth0_dbconnections_signup_b'
import type { post_auth0_oauth_token_T } from './post_auth0_oauth_token_b'
import { post_auth0_oauth_token_b } from './post_auth0_oauth_token_b'
import type { post_auth0_passwordless_start_T } from './post_auth0_passwordless_start_b'
import { post_auth0_passwordless_start_b } from './post_auth0_passwordless_start_b'
import type { set_auth0_token_T } from './set_auth0_token_b'
import { set_auth0_token_b } from './set_auth0_token_b'
import type { verify_id_token_header_authorization__T } from './verify_id_token_header_authorization__b'
import { verify_id_token_header_authorization__b } from './verify_id_token_header_authorization__b'
export interface auth0_ctx_I {
	AUTH0_CLIENT_ID$?:AUTH0_CLIENT_ID$_T
	AUTH0_DOMAIN$?:AUTH0_DOMAIN$_T
	AUTH0_URL$?:AUTH0_URL$_T
	auth0_change_password_opened$?:auth0_change_password_opened$_T
	auth0_closed$?:auth0_closed$_T
	auth0_email$?:auth0_email$_T
	auth0_forgot_password_check_email_opened$?:auth0_forgot_password_check_email_opened$_T
	auth0_forgot_password_opened$?:auth0_forgot_password_opened$_T
	auth0_login_opened$?:auth0_login_opened$_T
	auth0_logout_msg$?:auth0_logout_msg$_T
	auth0_opened$?:auth0_opened$_T
	auth0_opened_class$?:auth0_opened_class$_T
	auth0_signup_opened$?:auth0_signup_opened$_T
	auth0_token$?:auth0_token$_T
	auth0_token_error$?:auth0_token_error$_T
	auth0_token_error_txt$?:auth0_token_error_txt$_T
	auth0_token_json$?:auth0_token_json$_T
	auth0_userinfo$?:auth0_userinfo$_T
	auth0_userinfo_auth0_token$?:auth0_userinfo_auth0_token$_T
	auth0_userinfo_ctx$?:auth0_userinfo_ctx$_T
	clear_auth0_token?:clear_auth0_token_T
	clear_auth0_token_error?:clear_auth0_token_error_T
	close_auth0?:close_auth0_T
	get_jwks_json?:get_jwks_json_T
	in_auth0_token$?:in_auth0_token$_T
	is_auth0_loggedin$?:is_auth0_loggedin$_T
	is_auth0_loggedout$?:is_auth0_loggedout$_T
	logout_auth0_token?:logout_auth0_token_T
	logout_auth0_token_error?:logout_auth0_token_error_T
	open_auth0_forgot_password?:open_auth0_forgot_password_T
	open_auth0_forgot_password_check_email?:open_auth0_forgot_password_check_email_T
	open_auth0_login?:open_auth0_login_T
	open_auth0_signup?:open_auth0_signup_T
	post_auth0_auth_change_password?:post_auth0_auth_change_password_T
	post_auth0_dbconnections_change_password?:post_auth0_dbconnections_change_password_T
	post_auth0_dbconnections_signup?:post_auth0_dbconnections_signup_T
	post_auth0_oauth_token?:post_auth0_oauth_token_T
	post_auth0_passwordless_start?:post_auth0_passwordless_start_T
	set_auth0_token?:set_auth0_token_T
	verify_id_token_header_authorization_?:verify_id_token_header_authorization__T
	auth0_b_h?:auth0_b_h_T
}
export interface auth0_b_h_T {
	get AUTH0_CLIENT_ID$():AUTH0_CLIENT_ID$_T
	get AUTH0_DOMAIN$():AUTH0_DOMAIN$_T
	get AUTH0_URL$():AUTH0_URL$_T
	get auth0_change_password_opened$():auth0_change_password_opened$_T
	get auth0_closed$():auth0_closed$_T
	get auth0_email$():auth0_email$_T
	get auth0_forgot_password_check_email_opened$():auth0_forgot_password_check_email_opened$_T
	get auth0_forgot_password_opened$():auth0_forgot_password_opened$_T
	get auth0_login_opened$():auth0_login_opened$_T
	get auth0_logout_msg$():auth0_logout_msg$_T
	get auth0_opened$():auth0_opened$_T
	get auth0_opened_class$():auth0_opened_class$_T
	get auth0_signup_opened$():auth0_signup_opened$_T
	get auth0_token$():auth0_token$_T
	get auth0_token_error$():auth0_token_error$_T
	get auth0_token_error_txt$():auth0_token_error_txt$_T
	get auth0_token_json$():auth0_token_json$_T
	get auth0_userinfo$():auth0_userinfo$_T
	get auth0_userinfo_auth0_token$():auth0_userinfo_auth0_token$_T
	get auth0_userinfo_ctx$():auth0_userinfo_ctx$_T
	get clear_auth0_token():clear_auth0_token_T
	get clear_auth0_token_error():clear_auth0_token_error_T
	get close_auth0():close_auth0_T
	get get_jwks_json():get_jwks_json_T
	get in_auth0_token$():in_auth0_token$_T
	get is_auth0_loggedin$():is_auth0_loggedin$_T
	get is_auth0_loggedout$():is_auth0_loggedout$_T
	get logout_auth0_token():logout_auth0_token_T
	get logout_auth0_token_error():logout_auth0_token_error_T
	get open_auth0_forgot_password():open_auth0_forgot_password_T
	get open_auth0_forgot_password_check_email():open_auth0_forgot_password_check_email_T
	get open_auth0_login():open_auth0_login_T
	get open_auth0_signup():open_auth0_signup_T
	get post_auth0_auth_change_password():post_auth0_auth_change_password_T
	get post_auth0_dbconnections_change_password():post_auth0_dbconnections_change_password_T
	get post_auth0_dbconnections_signup():post_auth0_dbconnections_signup_T
	get post_auth0_oauth_token():post_auth0_oauth_token_T
	get post_auth0_passwordless_start():post_auth0_passwordless_start_T
	get set_auth0_token():set_auth0_token_T
	get verify_id_token_header_authorization_():verify_id_token_header_authorization__T
}
export function auth0_b_h_b(ctx:auth0_Ctx):auth0_b_h_T {
	return be_<auth0_Ctx, 'auth0_b_h'>('auth0_b_h', ()=>{
		return {
			get AUTH0_CLIENT_ID$() { return AUTH0_CLIENT_ID$_b(ctx) },
			get AUTH0_DOMAIN$() { return AUTH0_DOMAIN$_b(ctx) },
			get AUTH0_URL$() { return AUTH0_URL$_b(ctx) },
			get auth0_change_password_opened$() { return auth0_change_password_opened$_b(ctx) },
			get auth0_closed$() { return auth0_closed$_b(ctx) },
			get auth0_email$() { return auth0_email$_b(ctx) },
			get auth0_forgot_password_check_email_opened$() { return auth0_forgot_password_check_email_opened$_b(ctx) },
			get auth0_forgot_password_opened$() { return auth0_forgot_password_opened$_b(ctx) },
			get auth0_login_opened$() { return auth0_login_opened$_b(ctx) },
			get auth0_logout_msg$() { return auth0_logout_msg$_b(ctx) },
			get auth0_opened$() { return auth0_opened$_b(ctx) },
			get auth0_opened_class$() { return auth0_opened_class$_b(ctx) },
			get auth0_signup_opened$() { return auth0_signup_opened$_b(ctx) },
			get auth0_token$() { return auth0_token$_b(ctx) },
			get auth0_token_error$() { return auth0_token_error$_b(ctx) },
			get auth0_token_error_txt$() { return auth0_token_error_txt$_b(ctx) },
			get auth0_token_json$() { return auth0_token_json$_b(ctx) },
			get auth0_userinfo$() { return auth0_userinfo$_b(ctx) },
			get auth0_userinfo_auth0_token$() { return auth0_userinfo_auth0_token$_b(ctx) },
			get auth0_userinfo_ctx$() { return auth0_userinfo_ctx$_b(ctx) },
			get clear_auth0_token() { return clear_auth0_token_b(ctx) },
			get clear_auth0_token_error() { return clear_auth0_token_error_b(ctx) },
			get close_auth0() { return close_auth0_b(ctx) },
			get get_jwks_json() { return get_jwks_json_b(ctx) },
			get in_auth0_token$() { return in_auth0_token$_b(ctx) },
			get is_auth0_loggedin$() { return is_auth0_loggedin$_b(ctx) },
			get is_auth0_loggedout$() { return is_auth0_loggedout$_b(ctx) },
			get logout_auth0_token() { return logout_auth0_token_b(ctx) },
			get logout_auth0_token_error() { return logout_auth0_token_error_b(ctx) },
			get open_auth0_forgot_password() { return open_auth0_forgot_password_b(ctx) },
			get open_auth0_forgot_password_check_email() { return open_auth0_forgot_password_check_email_b(ctx) },
			get open_auth0_login() { return open_auth0_login_b(ctx) },
			get open_auth0_signup() { return open_auth0_signup_b(ctx) },
			get post_auth0_auth_change_password() { return post_auth0_auth_change_password_b(ctx) },
			get post_auth0_dbconnections_change_password() { return post_auth0_dbconnections_change_password_b(ctx) },
			get post_auth0_dbconnections_signup() { return post_auth0_dbconnections_signup_b(ctx) },
			get post_auth0_oauth_token() { return post_auth0_oauth_token_b(ctx) },
			get post_auth0_passwordless_start() { return post_auth0_passwordless_start_b(ctx) },
			get set_auth0_token() { return set_auth0_token_b(ctx) },
			get verify_id_token_header_authorization_() { return verify_id_token_header_authorization__b(ctx) }
		}
	})(ctx)
}