/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { AUTH0_CLIENT_ID$_T } from './AUTH0_CLIENT_ID$_b'
import type { AUTH0_DOMAIN$_T } from './AUTH0_DOMAIN$_b'
import type { AUTH0_URL$_T } from './AUTH0_URL$_b'
import type { auth0_change_password_opened$_T } from './auth0_change_password_opened$_b'
import type { auth0_closed$_T } from './auth0_closed$_b'
import type { auth0_email$_T } from './auth0_email$_b'
import type { auth0_forgot_password_check_email_opened$_T } from './auth0_forgot_password_check_email_opened$_b'
import type { auth0_forgot_password_opened$_T } from './auth0_forgot_password_opened$_b'
import type { auth0_login_opened$_T } from './auth0_login_opened$_b'
import type { auth0_logout_msg$_T } from './auth0_logout_msg$_b'
import type { auth0_opened$_T } from './auth0_opened$_b'
import type { auth0_opened_class$_T } from './auth0_opened_class$_b'
import type { auth0_signup_opened$_T } from './auth0_signup_opened$_b'
import type { auth0_token$_T } from './auth0_token$_b'
import type { auth0_token_error$_T } from './auth0_token_error$_b'
import type { auth0_token_error_txt$_T } from './auth0_token_error_txt$_b'
import type { auth0_token_json$_T } from './auth0_token_json$_b'
import type { auth0_userinfo$_T } from './auth0_userinfo$_b'
import type { auth0_userinfo_auth0_token$_T } from './auth0_userinfo_auth0_token$_b'
import type { auth0_userinfo_ctx$_T } from './auth0_userinfo_ctx$_b'
import type { clear_auth0_token_T } from './clear_auth0_token_b'
import type { clear_auth0_token_error_T } from './clear_auth0_token_error_b'
import type { close_auth0_T } from './close_auth0_b'
import type { get_jwks_json_T } from './get_jwks_json_b'
import type { in_auth0_token$_T } from './in_auth0_token$_b'
import type { is_auth0_loggedin$_T } from './is_auth0_loggedin$_b'
import type { is_auth0_loggedout$_T } from './is_auth0_loggedout$_b'
import type { logout_auth0_token_T } from './logout_auth0_token_b'
import type { logout_auth0_token_error_T } from './logout_auth0_token_error_b'
import type { open_auth0_forgot_password_T } from './open_auth0_forgot_password_b'
import type { open_auth0_forgot_password_check_email_T } from './open_auth0_forgot_password_check_email_b'
import type { open_auth0_login_T } from './open_auth0_login_b'
import type { open_auth0_signup_T } from './open_auth0_signup_b'
import type { post_auth0_auth_change_password_T } from './post_auth0_auth_change_password_b'
import type { post_auth0_dbconnections_change_password_T } from './post_auth0_dbconnections_change_password_b'
import type { post_auth0_dbconnections_signup_T } from './post_auth0_dbconnections_signup_b'
import type { post_auth0_oauth_token_T } from './post_auth0_oauth_token_b'
import type { post_auth0_passwordless_start_T } from './post_auth0_passwordless_start_b'
import type { set_auth0_token_T } from './set_auth0_token_b'
import type { verify_id_token_header_authorization__T } from './verify_id_token_header_authorization__b'
export interface auth0_ctx_I {
	AUTH0_CLIENT_ID$?:AUTH0_CLIENT_ID$_T
	AUTH0_DOMAIN$?:AUTH0_DOMAIN$_T
	AUTH0_URL$?:AUTH0_URL$_T
	auth0_change_password_opened$?:auth0_change_password_opened$_T
	auth0_closed$?:auth0_closed$_T
	auth0_email$?:auth0_email$_T
	auth0_forgot_password_check_email_opened$?:auth0_forgot_password_check_email_opened$_T
	auth0_forgot_password_opened$?:auth0_forgot_password_opened$_T
	auth0_login_opened$?:auth0_login_opened$_T
	auth0_logout_msg$?:auth0_logout_msg$_T
	auth0_opened$?:auth0_opened$_T
	auth0_opened_class$?:auth0_opened_class$_T
	auth0_signup_opened$?:auth0_signup_opened$_T
	auth0_token$?:auth0_token$_T
	auth0_token_error$?:auth0_token_error$_T
	auth0_token_error_txt$?:auth0_token_error_txt$_T
	auth0_token_json$?:auth0_token_json$_T
	auth0_userinfo$?:auth0_userinfo$_T
	auth0_userinfo_auth0_token$?:auth0_userinfo_auth0_token$_T
	auth0_userinfo_ctx$?:auth0_userinfo_ctx$_T
	clear_auth0_token?:clear_auth0_token_T
	clear_auth0_token_error?:clear_auth0_token_error_T
	close_auth0?:close_auth0_T
	get_jwks_json?:get_jwks_json_T
	in_auth0_token$?:in_auth0_token$_T
	is_auth0_loggedin$?:is_auth0_loggedin$_T
	is_auth0_loggedout$?:is_auth0_loggedout$_T
	logout_auth0_token?:logout_auth0_token_T
	logout_auth0_token_error?:logout_auth0_token_error_T
	open_auth0_forgot_password?:open_auth0_forgot_password_T
	open_auth0_forgot_password_check_email?:open_auth0_forgot_password_check_email_T
	open_auth0_login?:open_auth0_login_T
	open_auth0_signup?:open_auth0_signup_T
	post_auth0_auth_change_password?:post_auth0_auth_change_password_T
	post_auth0_dbconnections_change_password?:post_auth0_dbconnections_change_password_T
	post_auth0_dbconnections_signup?:post_auth0_dbconnections_signup_T
	post_auth0_oauth_token?:post_auth0_oauth_token_T
	post_auth0_passwordless_start?:post_auth0_passwordless_start_T
	set_auth0_token?:set_auth0_token_T
	verify_id_token_header_authorization_?:verify_id_token_header_authorization__T
}